import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // let session = getSession().then(console.log);
  // console.log("FAC", session);
  let session = await getServerSession();
  return (
    <html lang="en">
      <body className="dark:bg-[#262626] dark:text-white min-h-screen">
        <SessionProvider session={session}>
          <Header session={session} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
